Update GitHub action to support Docker image id input (#3)

diff --git a/.github/workflows/jepsen.yml b/.github/workflows/jepsen.yml
--- a/.github/workflows/jepsen.yml
+++ b/.github/workflows/jepsen.yml
@@ -2,20 +2,37 @@ name: Jepsen tests
 on:
   workflow_dispatch:
     inputs:
-      retainCluster:
-        description: 'Keeps the AWS Jepsen worker cluster running after the test is complete. Subsequent test runs will reuse it.'
+      restateImageId:
+        description: 'Restate Docker image to use for test'
         required: false
-        type: boolean
+        default: 'ghcr.io/restatedev/restate:main'
+        type: string
+      restateCommit:
+        description: 'Restate commit id - will download the Docker image artifact produced by its CI workflow'
+        required: false
+        default: ''
+        type: string
+      restatePr:
+        description: 'Restate PR number - will download the Docker image artifact produced by its CI workflow'
+        required: false
+        default: ''
+        type: string
       workloads:
-        description: 'List of workloads to run'
+        description: 'List of space-delimited workloads to run'
         required: false
+        default: 'set-vo set-mds'
         type: string
       nemeses:
-        description: 'List of nemeses to apply'
+        description: 'List of space-delimited nemeses to apply'
         required: false
+        default: 'none'
         type: string
+      retainCluster:
+        description: 'Retain the AWS worker node cluster after test'
+        required: false
+        type: boolean
   push:
-    branches: [ "main", "github-action" ]
+    branches: [ "main" ]
 
 permissions:
   id-token: write
@@ -52,14 +69,32 @@ jobs:
       - name: Build SDK services
         run: just make-services
 
+      - name: Download Restate Docker image
+        if: ${{ (inputs.restateCommit != '' || inputs.restatePr != '') && github.event_name == 'workflow_dispatch' }}
+        uses: dawidd6/action-download-artifact@v8
+        with:
+          repo: restatedev/restate
+          workflow: ci.yml
+          pr: ${{ inputs.restatePr }}
+          commit: ${{ inputs.restateCommit }}
+          name: restate.tar
+
+      - name: Test run Restate image on build worker
+        if: ${{ (inputs.restateCommit != '' || inputs.restatePr != '') && github.event_name == 'workflow_dispatch' }}
+        run: |
+          output=$(docker load --input restate.tar)
+          docker tag "${output#*: }" "localhost/restatedev/restate-commit-download:latest"
+          docker image ls -a
+          docker run localhost/restatedev/restate-commit-download:latest --help
+
+      # TODO: restrict the cluster to only be accessible to the build worker
+      #- run: curl -s https://checkip.amazonaws.com
+
       - uses: aws-actions/configure-aws-credentials@v4
         with:
           # Co-locate the cluster with WarpBuild:
           aws-region: us-east-1
           role-to-assume: arn:aws:iam::339713187748:role/github-restatedev-jepsen-actions-role
-
-      # TODO: restrict the cluster to only be accessible to the build worker
-      #- run: curl -s https://checkip.amazonaws.com
 
       - name: Create test cluster
         id: create-cluster
@@ -68,21 +103,35 @@ jobs:
       - name: Run Jepsen tests
         id: jepsen-tests
         run: |
-          status=0
-          for workload in ${{ inputs.workloads || 'set-vo' }}; do
-            for nemesis in ${{ inputs.nemeses || 'none partition-random-node' }}; do
+          if [ -f restate.tar ]; then
+            JEPSEN_RESTATE_IMAGE='--image localhost/restatedev/restate-commit-download:latest --image-tarball restate.tar'
+          else
+            JEPSEN_RESTATE_IMAGE='--image ${{ inputs.restateImageId || 'ghcr.io/restatedev/restate:main' }}'
+          fi
+
+          STATUS=0
+
+          for WORKLOAD in ${{ inputs.workloads || 'set-vo' }}; do
+            for NEMESIS in ${{ inputs.nemeses || 'none partition-random-node' }}; do
+              echo "::group::Jepsen workload: ${WORKLOAD} nemesis: ${NEMESIS}"
+
               lein run test \
                 --nodes-file aws/nodes.txt --username admin --ssh-private-key aws/private-key.pem \
-                --image ghcr.io/restatedev/restate:main \
-                --workload ${workload} --nemesis ${nemesis} \
-                --time-limit 30 --rate 10 --concurrency 5n
+                --workload ${WORKLOAD} --nemesis ${NEMESIS} \
+                ${JEPSEN_RESTATE_IMAGE} \
+                --time-limit 30 --rate 10 --concurrency 5n \
+                --leave-db-running ${{ inputs.retainCluster || 'false' }}
+
               if [ $? -ne 0 ]; then
-                echo "::error::Test failed"
-                status=1
+                STATUS=1
+                echo "::error::Test workload: ${WORKLOAD} nemesis: ${NEMESIS} failed" 
               fi
+
+              echo "::endgroup::"
             done
           done
-          exit ${status}
+
+          exit ${STATUS}
         timeout-minutes: 10
 
       - name: Upload Jepsen output
